export const ADD_INGREDIENTS= 'ADD_INGREDIENTS'
export const   REMOVE_INGREDIENTS= 'REMOVE_INGREDIENTS'
export const   SET_INGREDIENTS= 'SET_INGREDIENTS'
export const   FAILED_FETCH= 'FAILED_FETCH'

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const  PURCHASE_SUCCESS = 'PURCHASE_SUCCESS'
export const  PURCHASE_FAILURE = 'PURCHASE_FAILURE'
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_START ='FETCH_START'
export const FETCH_SUCCESS ='FETCH_SUCCESS'
export const FETCH_FAILURE ='FETCH_FAILURE'
export const FETCH_INIT ='FETCH_INIT'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'
export const LOGOUT   ='LOGOUT'

// export const DELETE_ORDER =' DELETE_ORDER'
// export const DELETE_SUCCESS =' DELETE_SUCCESS'
// export const DELETE_FAILURE =' DELETE_FAILURE'